owner: amblerapp
repo: status-toolkit

sites:
  - name: SVG to PNG
    url: https://svg-to-png.ambler.app/
  - name: SVG to PNG (Render)
    url: $SVGTOPNG_RENDER

status-website:
  cname: toolkit.status.ambler.app
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Toolkit Status | Ambler App
  introTitle: "**Upptime** for Toolkit"
  introMessage: 웹 툴킷 모니터
